### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by kirkngreta** [Nielk1/GameLaunchProxy#6]
Verified issue and settings with Camel through teamviewer...unable to get current version to process correctly and will not launch. Seems almost like proxy is not allocating names to the files to launch...but thats just a stab in the dark. Log below. 

2b3c0c88-88a0-4e73-becd-1c18b254ae25	Start
2b3c0c88-88a0-4e73-becd-1c18b254ae25	Version 0.0.5.0
2b3c0c88-88a0-4e73-becd-1c18b254ae25	Raw Command Line	"C:\Proxy\GameLaunchProxy.exe" -steam -gameid 1f505be1-22a2-4cb1-bb70-d2900782539f -name "%gamename% (%platformname%)" -fallbackname "%platformname%" -proxy "C:\Emulation\Emulators\RetroArch\retroarch.exe" -L "cores\desmume_libretro.dll" "C:\Emulation\Roms\Nds\Advance Wars - Days of Ruin.nds"
2b3c0c88-88a0-4e73-becd-1c18b254ae25	Possible Name Matches:
2b3c0c88-88a0-4e73-becd-1c18b254ae25		Advance Wars: Days of Ruin	Nintendo DS	1f505be1-22a2-4cb1-bb70-d2900782539f
2b3c0c88-88a0-4e73-becd-1c18b254ae25	-name Contains %gamename% or %platformname%
2b3c0c88-88a0-4e73-becd-1c18b254ae25	New -name	Advance Wars: Days of Ruin (Nintendo DS)
2b3c0c88-88a0-4e73-becd-1c18b254ae25	-fallbackname Contains %gamename% or %platformname%
2b3c0c88-88a0-4e73-becd-1c18b254ae25	New -fallbackname	Nintendo DS
2b3c0c88-88a0-4e73-becd-1c18b254ae25	Looking for steam shortcut
2b3c0c88-88a0-4e73-becd-1c18b254ae25	Shotcuts must path to "C:\Proxy\SteamProxy.exe"
2b3c0c88-88a0-4e73-becd-1c18b254ae25	Search Patterns:
2b3c0c88-88a0-4e73-becd-1c18b254ae25		Advance Wars: Days of Ruin (Nintendo DS)	
2b3c0c88-88a0-4e73-becd-1c18b254ae25		SteamProxy	<rename>
2b3c0c88-88a0-4e73-becd-1c18b254ae25		Nintendo DS	
2b3c0c88-88a0-4e73-becd-1c18b254ae25		SteamProxy	
2b3c0c88-88a0-4e73-becd-1c18b254ae25	Searching for item #0
2b3c0c88-88a0-4e73-becd-1c18b254ae25	Something went very wrong	System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at GameLaunchProxy.VPropertyCollection.get_Item(String key) in D:\Data\Programming\Projects\GameLaunchProxy\GameLaunchProxy\SteamShortcutDataFile.cs:line 266
   at GameLaunchProxy.SteamContext.GetShortcutID(String appname, String exe, String shortcutFilePath) in D:\Data\Programming\Projects\GameLaunchProxy\GameLaunchProxy\SteamContext.cs:line 499
   at GameLaunchProxy.Program.Main(String[] args) in D:\Data\Programming\Projects\GameLaunchProxy\GameLaunchProxy\Program.cs:line 331
2b3c0c88-88a0-4e73-becd-1c18b254ae25	Sequence contains no elements
2b3c0c88-88a0-4e73-becd-1c18b254ae25	Done looking for steam shortcut

**Comment by Kekker-git** [comment]
I've been having this same issue. My log has the same output.

**Comment by ChiefParzival** [comment]
Similar problem.

c9ec6ee3-d59f-42ca-b5af-5d2902f68021	Start
c9ec6ee3-d59f-42ca-b5af-5d2902f68021	Version 0.0.5.0
c9ec6ee3-d59f-42ca-b5af-5d2902f68021	Raw Command Line	"D:\Games\Proxy\GameLaunchProxy.exe" -steam -name %gamename% (%platformname%) -proxy "D:\Games\Emulators\GamecubeWii\Dolphin\Dolphin.exe" -b -e "D:\Games\LaunchBox\Games\Nintendo GameCube\Alien Hominid-1.iso"
c9ec6ee3-d59f-42ca-b5af-5d2902f68021	Possible Name Matches:
c9ec6ee3-d59f-42ca-b5af-5d2902f68021	-name Contains %gamename% or %platformname%
c9ec6ee3-d59f-42ca-b5af-5d2902f68021	New -name	Alien Hominid-1
c9ec6ee3-d59f-42ca-b5af-5d2902f68021	Looking for steam shortcut
c9ec6ee3-d59f-42ca-b5af-5d2902f68021	Shotcuts must path to "D:\Games\Proxy\SteamProxy.exe"
c9ec6ee3-d59f-42ca-b5af-5d2902f68021	Search Patterns:
c9ec6ee3-d59f-42ca-b5af-5d2902f68021		Alien Hominid-1	
c9ec6ee3-d59f-42ca-b5af-5d2902f68021		SteamProxy	<rename>
c9ec6ee3-d59f-42ca-b5af-5d2902f68021		SteamProxy	
c9ec6ee3-d59f-42ca-b5af-5d2902f68021	Searching for item #0
c9ec6ee3-d59f-42ca-b5af-5d2902f68021	Something went very wrong	System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at GameLaunchProxy.VPropertyCollection.get_Item(String key) in D:\Data\Programming\Projects\GameLaunchProxy\GameLaunchProxy\SteamShortcutDataFile.cs:line 266
   at GameLaunchProxy.SteamContext.GetShortcutID(String appname, String exe, String shortcutFilePath) in D:\Data\Programming\Projects\GameLaunchProxy\GameLaunchProxy\SteamContext.cs:line 499
   at GameLaunchProxy.Program.Main(String[] args) in D:\Data\Programming\Projects\GameLaunchProxy\GameLaunchProxy\Program.cs:line 331
c9ec6ee3-d59f-42ca-b5af-5d2902f68021	Sequence contains no elements
c9ec6ee3-d59f-42ca-b5af-5d2902f68021	Done looking for steam shortcut
ebf9e389-561d-424b-9654-156d04368b33	Start
ebf9e389-561d-424b-9654-156d04368b33	Version 0.0.5.0
ebf9e389-561d-424b-9654-156d04368b33	Raw Command Line	"D:\Games\Proxy\GameLaunchProxy.exe" 
ebf9e389-561d-424b-9654-156d04368b33	Start GUI
